export interface IShowDetails {
  showTitle: string,
  showImage: string,
  showLink: string,
  rating: number,
  channel: string,
  country: string,
  genre: string,
  language: string,
  previousEpisode: string,
  premierDate: Date,
  summary: string,
  days: string,
  time: Date,
  castName1: string,
  castLink1: string,
  castImage1: string,
  castName2: string,
  castLink2: string,
  castImage2: string,
  castName3: string,
  castLink3: string,
  castImage3: string,
  castName4: string,
  castLink4: string,
  castImage4: string
}
